### PR TITLE
change theme to google's material design style

### PR DESCRIPTION
**Pull request by butaixianran**
change theme to google's material design style
I haven't found where I can change the header's github picture yet, so I upload the new one to the image folder.

### CODE REVIEW

**Comment by ivpusic** [comment]
Awesome! Thanks!

**Comment by butaixianran** [comment]
hi, would you also change the github image at right corner? I havn't found a place to change it, so for I just upload the new image to "image" folder

**Comment by ivpusic** [comment]
What color do you suggest?

**Comment by butaixianran** [comment]
Never mind, I just found the image tag to change it, I'll create a new pull request soon.

To follow google's material design standard, one page should not have more than 3 colors, so it will be material design's default theme's accent color.

**Pull request merged**
